apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: zu7jm7zkq-java-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zu7jm7zkq-java-quarkus 
  name: zu7jm7zkq-java-quarkus
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: zu7jm7zkq-java-quarkus
    weight: 100 
